const PKEY='phone_inventory_products_v1', IKEY='phone_inventory_phones_v1';
const demo=[{upc:'195950685784',model:'iPhone 16 Pro Max',color:'沙漠金色',capacity:'256GB'},{upc:'195950385417',model:'iPhone 16 Pro',color:'原色钛金属',capacity:'256GB'}];
let products=JSON.parse(localStorage.getItem(PKEY)||'null')||demo, phones=JSON.parse(localStorage.getItem(IKEY)||'[]');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], save=()=>{localStorage.setItem(PKEY,JSON.stringify(products));localStorage.setItem(IKEY,JSON.stringify(phones));render()};
const fmt=x=>new Date(x).toLocaleString('zh-CN',{hour12:false});
function stats(){const stock=phones.filter(x=>x.status==='库存中'),m={};stock.forEach(x=>{let k=[x.model,x.color,x.capacity].join(' · ');m[k]=(m[k]||0)+1});return {stock,list:Object.entries(m).sort((a,b)=>b[1]-a[1])}}
function render(){const s=stats(),today=new Date().toLocaleDateString('zh-CN');$('#stockCount').textContent=s.stock.length;$('#todayCount').textContent=phones.filter(x=>new Date(x.receivedAt).toLocaleDateString('zh-CN')===today).length;$('#shippedCount').textContent=phones.filter(x=>x.status==='已出库').length;$('#modelCount').textContent=s.list.length;
 $('#stats').innerHTML=s.list.length?s.list.slice(0,6).map(([k,n])=>`<div class="row"><span>${k}</span><b>${n}</b></div><div class="bar"><i style="width:${Math.max(8,n/s.stock.length*100)}%"></i></div>`).join(''):'<div class="empty">还没有库存数据</div>';
 $('#recent').innerHTML=phones.length?phones.slice(0,5).map(x=>`<div class="row"><span><b>${x.model}</b><br><span class="muted">${x.color} · ${x.capacity}</span></span><small>${x.imei.slice(-6)}</small></div>`).join(''):'<div class="empty">扫码入库后会显示在这里</div>';tables();productsTable()}
function rows(items,ship=false){return `<table><thead><tr><th>手机</th><th>IMEI</th><th>快递单号</th><th>UPC</th><th>状态</th><th>入库时间</th>${ship?'<th></th>':''}</tr></thead><tbody>`+items.map(x=>`<tr><td><b>${x.model}</b><br><span class="muted">${x.color} · ${x.capacity}</span></td><td>${x.imei}</td><td>${x.tracking}</td><td>${x.upc}</td><td><span class="tag">${x.status}</span></td><td>${fmt(x.receivedAt)}</td>${ship?`<td><button class="danger" data-ship="${x.imei}">确认出库</button></td>`:''}</tr>`).join('')+'</tbody></table>'}
function tables(q=''){let match=x=>[x.tracking,x.imei,x.upc,x.model,x.color,x.capacity].join(' ').toLowerCase().includes(q.toLowerCase());$('#stockTable').innerHTML=rows(phones.filter(match));$('#shipTable').innerHTML=rows(phones.filter(x=>x.status==='库存中'&&match(x)),true);$$('[data-ship]').forEach(b=>b.onclick=()=>{if(confirm('确认将这部手机标记为已出库？')){phones=phones.map(x=>x.imei===b.dataset.ship?{...x,status:'已出库',shippedAt:new Date().toISOString()}:x);save()}})}
function productsTable(){$('#productTable').innerHTML=`<table><thead><tr><th>UPC</th><th>型号</th><th>颜色</th><th>容量</th><th></th></tr></thead><tbody>`+products.map(x=>`<tr><td>${x.upc}</td><td><b>${x.model}</b></td><td>${x.color}</td><td>${x.capacity}</td><td><button class="delete" data-del="${x.upc}">删除</button></td></tr>`).join('')+'</tbody></table>';$$('[data-del]').forEach(b=>b.onclick=()=>{products=products.filter(x=>x.upc!==b.dataset.del);save()})}
function receive(){let tracking=$('#tracking').value.trim(),imei=$('#imei').value.trim(),upc=$('#upc').value.trim(),msg=$('#message');if(!tracking||!imei||!upc)return msg.textContent='三个条码都必须扫描';if(phones.some(x=>x.tracking===tracking))return msg.textContent='⚠️ 这个快递单号已经录入';if(phones.some(x=>x.imei===imei))return msg.textContent='⚠️ 这个 IMEI 已经录入';let p=products.find(x=>x.upc===upc);if(!p){msg.textContent='⚠️ UPC 型号库中没有这个代码，请先添加型号';show('products');$('#pUpc').value=upc;return}phones.unshift({...p,tracking,imei,status:'库存中',receivedAt:new Date().toISOString()});['tracking','imei','upc'].forEach(x=>$('#'+x).value='');msg.textContent=`✅ 已入库：${p.model} · ${p.color} · ${p.capacity}`;save();$('#tracking').focus()}
function show(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));let map={receive:['入库扫码','按顺序扫描三个条码，系统会自动跳到下一栏'],stock:['当前库存','查看所有手机的库存状态'],ship:['出库管理','搜索手机并确认出库'],products:['UPC 型号库','维护 UPC 与手机型号的对应关系']};$('#title').textContent=map[id][0];$('#subtitle').textContent=map[id][1]}
$$('nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#tracking').onkeydown=e=>{if(e.key==='Enter')$('#imei').focus()};$('#imei').onkeydown=e=>{if(e.key==='Enter')$('#upc').focus()};$('#upc').onkeydown=e=>{if(e.key==='Enter')receive()};$('#receiveBtn').onclick=receive;$$('.search').forEach(x=>x.oninput=()=>tables(x.value));
$('#productForm').onsubmit=e=>{e.preventDefault();let p={upc:$('#pUpc').value.trim(),model:$('#pModel').value.trim(),color:$('#pColor').value.trim(),capacity:$('#pCapacity').value.trim()};products=[p,...products.filter(x=>x.upc!==p.upc)];e.target.reset();save()};
$('#csvImport').onchange=e=>{let r=new FileReader;r.onload=()=>{let a=String(r.result).replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean).slice(1).map(x=>{let [upc,model,color,capacity]=x.split(',').map(v=>v.replace(/^"|"$/g,'').trim());return{upc,model,color,capacity}}).filter(x=>x.upc&&x.model);products=[...a,...products.filter(x=>!a.some(y=>y.upc===x.upc))];save()};if(e.target.files[0])r.readAsText(e.target.files[0])};
$('#export').onclick=()=>{let h=['快递单号','IMEI','UPC','型号','颜色','容量','状态','入库时间','出库时间'],esc=x=>'"'+String(x||'').replaceAll('"','""')+'"',data=[h,...phones.map(x=>[x.tracking,x.imei,x.upc,x.model,x.color,x.capacity,x.status,fmt(x.receivedAt),x.shippedAt?fmt(x.shippedAt):''])].map(r=>r.map(esc).join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+data],{type:'text/csv'}));a.download=`手机库存_${new Date().toISOString().slice(0,10)}.csv`;a.click()};render();$('#tracking').focus();
